FROM oven/bun:1
WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/http ./apps/http

RUN bun install
RUN bun run db:generate

EXPOSE 3001


CMD [ "bun","run","start:http"]