FROM oven/bun:1

WORKDIR /usr/src/app

COPY package.json ./package.json
COPY bun.lock ./bun.lock
COPY turbo.json ./turbo.json

COPY packages ./packages
COPY apps/backend ./apps/backend

RUN bun install

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN bun run db:generate

EXPOSE 3001

CMD ["bun","run","start:backend"]

#  docker build -t todo-app-backend -f ./docker/Dockerfile.backend .